In [ ]:
%cd /home/parthgandhi/Projects/SwingBot/swingbot/src

In [ ]:
import polars as pl
from config.ingestion.brokers import KiteConfig
from datetime import datetime
from ingestion import fetch_nse_indices
from computation.compute import gen_market_dashboard_data

In [ ]:
SCAN_DATE = datetime(2026, 3, 13)

# Get Indices Constituents

In [ ]:
nse_indices_df = fetch_nse_indices(download_flag=False)
nse_indices_df.head()

# Get Stock & Indices Data

In [ ]:
stock_table_id = KiteConfig.get_db_tbl(
    data_type=KiteConfig.TYP_STOCKS, frequency="day", failed_tbl=False
)
indices_table_id = KiteConfig.get_db_tbl(
    data_type=KiteConfig.TYP_INDICES, frequency="day", failed_tbl=False
)

In [6]:
query = f"""
select *
from {stock_table_id}
"""

stocks_df = pl.read_database_uri(query=query, uri=KiteConfig.DB_CONN)

query = f"""
select *
from {indices_table_id}
"""

indices_df = pl.read_database_uri(query=query, uri=KiteConfig.DB_CONN)

In [7]:
stocks_df.head()

shape: (5, 7)
┌────────────┬─────────────────────┬───────┬───────┬───────┬───────┬────────┐
│ symbol     ┆ timestamp           ┆ open  ┆ high  ┆ low   ┆ close ┆ volume │
│ ---        ┆ ---                 ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---    │
│ str        ┆ datetime[ns]        ┆ f64   ┆ f64   ┆ f64   ┆ f64   ┆ i64    │
╞════════════╪═════════════════════╪═══════╪═══════╪═══════╪═══════╪════════╡
│ 21STCENMGM ┆ 2025-03-19 00:00:00 ┆ 62.63 ┆ 63.9  ┆ 62.63 ┆ 62.63 ┆ 9760   │
│ 21STCENMGM ┆ 2025-03-20 00:00:00 ┆ 61.5  ┆ 63.85 ┆ 61.5  ┆ 62.44 ┆ 5768   │
│ 21STCENMGM ┆ 2025-03-21 00:00:00 ┆ 62.44 ┆ 63.68 ┆ 62.35 ┆ 63.5  ┆ 16853  │
│ 21STCENMGM ┆ 2025-03-24 00:00:00 ┆ 64.77 ┆ 64.77 ┆ 64.77 ┆ 64.77 ┆ 1574   │
│ 21STCENMGM ┆ 2025-03-25 00:00:00 ┆ 66.06 ┆ 66.06 ┆ 66.06 ┆ 66.06 ┆ 4786   │
└────────────┴─────────────────────┴───────┴───────┴───────┴───────┴────────┘

In [8]:
indices_df.head()

shape: (5, 7)
┌──────────┬─────────────────────┬──────────┬──────────┬──────────┬──────────┬────────┐
│ symbol   ┆ timestamp           ┆ open     ┆ high     ┆ low      ┆ close    ┆ volume │
│ ---      ┆ ---                 ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---    │
│ str      ┆ datetime[ns]        ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ i64    │
╞══════════╪═════════════════════╪══════════╪══════════╪══════════╪══════════╪════════╡
│ NIFTY 50 ┆ 2025-03-19 00:00:00 ┆ 22874.95 ┆ 22940.7  ┆ 22807.95 ┆ 22907.6  ┆ 0      │
│ NIFTY 50 ┆ 2025-03-20 00:00:00 ┆ 23036.6  ┆ 23216.7  ┆ 22973.95 ┆ 23190.65 ┆ 0      │
│ NIFTY 50 ┆ 2025-03-21 00:00:00 ┆ 23168.25 ┆ 23402.7  ┆ 23132.8  ┆ 23350.4  ┆ 0      │
│ NIFTY 50 ┆ 2025-03-24 00:00:00 ┆ 23515.4  ┆ 23708.75 ┆ 23433.5  ┆ 23658.35 ┆ 0      │
│ NIFTY 50 ┆ 2025-03-25 00:00:00 ┆ 23751.5  ┆ 23869.6  ┆ 23601.4  ┆ 23668.65 ┆ 0      │
└──────────┴─────────────────────┴──────────┴──────────┴──────────┴──────────┴────────┘

# Market Dashboard Data

In [23]:
mkt_db_stocks_df, mkt_db_indices_df = gen_market_dashboard_data(
    nse_indices_df=nse_indices_df,
    indices_df=indices_df,
    stocks_df=stocks_df,
    scan_date=SCAN_DATE,
)